# Generated by Django 3.1.7 on 2021-04-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_master_fees'),
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry_details',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='inquiry', to='course.course_master'),
        ),
    ]
