# Generated by Django 3.1.7 on 2021-04-09 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmission_details',
            name='date_of_addmission',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
