# Generated by Django 3.1.7 on 2021-05-03 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_auto_20210503_1000'),
        ('addmission', '0002_auto_20210409_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmission_details',
            name='inquiry',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='addmission', to='inquiry.inquiry_details'),
        ),
    ]
