# Generated by Django 3.1.7 on 2021-05-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission', '0003_addmission_details_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmission_details',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On hold', 'On hold'), ('Close', 'Close')], max_length=10),
        ),
    ]
