# Generated by Django 3.1.7 on 2021-04-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_personal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=30)),
                ('student_last_name', models.CharField(max_length=30)),
                ('student_second_name', models.CharField(max_length=30)),
                ('father_first_name', models.CharField(max_length=30)),
                ('father_second_name', models.CharField(max_length=30)),
                ('father_last_name', models.CharField(max_length=30)),
                ('houseno_building_name', models.TextField()),
                ('st_name', models.CharField(max_length=30)),
                ('area_name', models.CharField(max_length=30)),
                ('city_name', models.CharField(max_length=30)),
                ('country_name', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=11)),
                ('phone_number_house', models.CharField(max_length=11)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('school_college_name', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='images')),
                ('biomatric_data', models.CharField(max_length=30)),
                ('email_id', models.CharField(max_length=30)),
                ('inquiry_id', models.IntegerField()),
            ],
        ),
    ]
