# Generated by Django 3.1.7 on 2021-04-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.IntegerField()),
                ('receipt_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('Cash', 'Cash'), ('Chaque', 'Chaque')], max_length=10)),
                ('chaque_no', models.IntegerField()),
                ('bank_name', models.CharField(max_length=30)),
                ('branch_name', models.CharField(max_length=30)),
                ('chaque_date', models.DateField()),
            ],
        ),
    ]
