# Generated by Django 3.1.7 on 2021-04-22 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addmission', '0002_auto_20210409_0914'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_details',
            name='addmission',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='addmission.addmission_details'),
        ),
        migrations.AlterField(
            model_name='payment_details',
            name='bank_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='payment_details',
            name='branch_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='payment_details',
            name='chaque_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment_details',
            name='chaque_no',
            field=models.IntegerField(blank=True),
        ),
    ]
