# Generated by Django 3.1.7 on 2021-04-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20210422_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='chaque_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
